project:
  type: website
  render:
    - "*.qmd"
    - "!posts/*/lesswrong.md"
  resources:
    - CNAME

website:
  description: "Personal page of Hubert Tomaszczak — machine learning security research at Fraunhofer HHI."
  site-url: https://hubertjan.de
  title: "Hubert Tomaszczak"
  navbar:
    right:
      - text: Blog
        href: index.qmd
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/hubertjan

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
