project:
  type: website
  resources:
    - CNAME

website:
  description: "Personal page of Hubert Tomaszczak — machine learning security research at Fraunhofer HHI."
  site-url: https://hubertjan.de
  title: "Hubert Tomaszczak"
  navbar: false
  page-navigation: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
