project:
  type: website
  render:
    - "*.qmd"
    - "!posts/*/lesswrong.md"
  resources:
    - CNAME

website:
  description: "Personal page of Hubert Tomaszczak — machine learning security research at Fraunhofer HHI."
  site-url: https://hubertjan.de
  title: "Hubert Tomaszczak"
  navbar:
    title: false
    background: light
    foreground: dark
    right:
      - text: Blog
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
      - theme.scss
    css: styles.css
    toc: false
